include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    always_specify_types: true
    always_use_package_imports: true
    avoid_escaping_inner_quotes: true
