name: dice_roller
description: "Animations for Dice Rolling using Flame"
version: 0.1.2
homepage: https://github.com/hotaydev/arcanapixel_dice_roller
license: AGPL-3.0

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

platforms:
  android:
  ios:
  web:
  macos:
  linux:
  windows:
